# Site
title: Qi's bolg                                                                                                                                                          
subtitle: '记录与分享'                                                                                                                                                         
description: '记录与分享'                                                                                                                                                    
author: youli                                                                                                                                                                  
language: zh-CN  

theme: fluid

deploy:
  type: git
  repo: https://github.com/qiqiqiyaya/qiqiqiyaya.github.io.git
  # example, https://github.com/hexojs/hexojs.github.io
  branch: main